/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IZtakingPool, IZtakingPoolInterface } from "../IZtakingPool";

const _abi = [
  {
    inputs: [],
    name: "CannotDepositForZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "CannotRenounceOwnership",
    type: "error",
  },
  {
    inputs: [],
    name: "DepositAmountCannotBeZero",
    type: "error",
  },
  {
    inputs: [],
    name: "DuplicateToken",
    type: "error",
  },
  {
    inputs: [],
    name: "MigratorAlreadyAllowedOrBlocked",
    type: "error",
  },
  {
    inputs: [],
    name: "MigratorBlocked",
    type: "error",
  },
  {
    inputs: [],
    name: "MigratorCannotBeZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "SignatureExpired",
    type: "error",
  },
  {
    inputs: [],
    name: "SignatureInvalid",
    type: "error",
  },
  {
    inputs: [],
    name: "SignerAlreadySetToAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "SignerCannotBeZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "TokenAlreadyConfiguredWithState",
    type: "error",
  },
  {
    inputs: [],
    name: "TokenArrayCannotBeEmpty",
    type: "error",
  },
  {
    inputs: [],
    name: "TokenCannotBeZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "TokenNotAllowedForStaking",
    type: "error",
  },
  {
    inputs: [],
    name: "UserDoesNotHaveStake",
    type: "error",
  },
  {
    inputs: [],
    name: "WETHCannotBeZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "WithdrawAmountCannotBeZero",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "migrator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "blocked",
        type: "bool",
      },
    ],
    name: "BlocklistChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "eventId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "depositor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "eventId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "tokens",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "address",
        name: "destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "migrator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "Migrate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newSigner",
        type: "address",
      },
    ],
    name: "SignerChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    name: "TokenStakabilityChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "eventId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "withdrawer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_migrator",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_blocklisted",
        type: "bool",
      },
    ],
    name: "blockMigrator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_for",
        type: "address",
      },
    ],
    name: "depositETHFor",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_for",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "depositFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_tokens",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "_migratorContract",
        type: "address",
      },
      {
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_signatureExpiry",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_authorizationSignatureFromZircuit",
        type: "bytes",
      },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "_tokens",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "_migratorContract",
        type: "address",
      },
      {
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_signatureExpiry",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_stakerSignature",
        type: "bytes",
      },
    ],
    name: "migrateWithSig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_canStake",
        type: "bool",
      },
    ],
    name: "setStakable",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_signer",
        type: "address",
      },
    ],
    name: "setZircuitSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IZtakingPool__factory {
  static readonly abi = _abi;
  static createInterface(): IZtakingPoolInterface {
    return new utils.Interface(_abi) as IZtakingPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IZtakingPool {
    return new Contract(address, _abi, signerOrProvider) as IZtakingPool;
  }
}
