/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MigratorDefault,
  MigratorDefaultInterface,
} from "../MigratorDefault";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "_tokens",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "_amounts",
        type: "uint256[]",
      },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061030a806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063abccc77e14610030575b600080fd5b61004361003e3660046101e6565b610045565b005b8381146100985760405162461bcd60e51b815260206004820152601f60248201527f4d69677261746f7244656661756c743a20494e56414c49445f4c454e47544800604482015260640160405180910390fd5b60005b84811015610175578585828181106100b5576100b561027a565b90506020020160208101906100ca9190610290565b6001600160a01b03166323b872dd33868686868181106100ec576100ec61027a565b6040516001600160e01b031960e088901b1681526001600160a01b039586166004820152949093166024850152506020909102013560448201526064016020604051808303816000875af1158015610148573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061016c91906102b2565b5060010161009b565b50505050505050565b80356001600160a01b038116811461019557600080fd5b919050565b60008083601f8401126101ac57600080fd5b50813567ffffffffffffffff8111156101c457600080fd5b6020830191508360208260051b85010111156101df57600080fd5b9250929050565b600080600080600080608087890312156101ff57600080fd5b6102088761017e565b9550602087013567ffffffffffffffff8082111561022557600080fd5b6102318a838b0161019a565b909750955085915061024560408a0161017e565b9450606089013591508082111561025b57600080fd5b5061026889828a0161019a565b979a9699509497509295939492505050565b634e487b7160e01b600052603260045260246000fd5b6000602082840312156102a257600080fd5b6102ab8261017e565b9392505050565b6000602082840312156102c457600080fd5b815180151581146102ab57600080fdfea2646970667358221220b6244fe87814c0c5d443bfe07a05613d67e482c0e1f04cab49b4a2233d3362b864736f6c63430008180033";

type MigratorDefaultConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MigratorDefaultConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MigratorDefault__factory extends ContractFactory {
  constructor(...args: MigratorDefaultConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "MigratorDefault";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MigratorDefault> {
    return super.deploy(overrides || {}) as Promise<MigratorDefault>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MigratorDefault {
    return super.attach(address) as MigratorDefault;
  }
  connect(signer: Signer): MigratorDefault__factory {
    return super.connect(signer) as MigratorDefault__factory;
  }
  static readonly contractName: "MigratorDefault";
  public readonly contractName: "MigratorDefault";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MigratorDefaultInterface {
    return new utils.Interface(_abi) as MigratorDefaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MigratorDefault {
    return new Contract(address, _abi, signerOrProvider) as MigratorDefault;
  }
}
